### ISSUE TITLE
[EPIC] Improve impact upon cracking joint

### ISSUE THREAD

**Issue by germainelee** [smkrexus/GGJ2024-UE5#70]
- [ ] Add more audio reaction types
- [ ] Camera & rig animation (snowbreak ulti skill / mortal combat fatality)
- [ ] Different language than normal after crack
- [ ] Emoji icon to represent patient facial expression / emotion
- [ ] Censored words
- [ ] Live stream audience reactions

**Comment by smkrexus** [comment]
https://www.youtube.com/shorts/6EFJAalWf08

might be a funny twist on #44
